docs_dir: docs
site_dir: site
site_name: Infopsychismus – An Integrative Book on Consciousness, Reality, and Meaning
site_description: An exploration of consciousness, reality, and meaning through an integrative philosophical approach
site_author: alkhemeia
site_url: https://alkhemeia.github.io/Infopsychismus/
repo_url: https://github.com/alkhemeia/Infopsychismus
repo_name: alkhemeia/Infopsychismus
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
  - tags

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: README.md
  - Book Overview: Infopsychismus_Book.md
  - Book Chapters:
      - Table of Contents: Infopsychismus_Book/00_Table_of_Contents.md
      - Introduction: Infopsychismus_Book/01_Introduction.md
      - The Question of Existence: Infopsychismus_Book/02_The_Question_of_Existence.md
      - The Structure of Reality: Infopsychismus_Book/03_The_Structure_of_Reality.md
      - The Role of Consciousness: Infopsychismus_Book/04_The_Role_of_Consciousness.md
      - Why Are We Conscious Beings Here?: Infopsychismus_Book/05_Why_Are_We_Conscious_Beings_Here.md
      - Our Actual Task: Infopsychismus_Book/06_Our_Actual_Task.md
      - Outlook and Ethical Implications: Infopsychismus_Book/07_Outlook_and_Ethical_Implications.md
      - The Future of Consciousness: Infopsychismus_Book/08_The_Future_of_Consciousness.md
      - Open Questions and Future Research Directions: Infopsychismus_Book/09_Open_Questions_and_Future_Research_Directions.md
      - Historical Context and Intellectual Lineage: Infopsychismus_Book/10_Historical_Context_and_Intellectual_Lineage.md
      - Case Studies and Real-World Applications: Infopsychismus_Book/11_Case_Studies_and_Real-World_Applications.md
      - Criticisms and Counterarguments: Infopsychismus_Book/12_Criticisms_and_Counterarguments.md
      - Methodology and Epistemology: Infopsychismus_Book/13_Methodology_and_Epistemology.md
      - Deeper Exploration of Ethics: Infopsychismus_Book/14_Deeper_Exploration_of_Ethics.md
      - Annexes and Further Reading: Infopsychismus_Book/15_Annexes_and_Further_Reading.md
      - Infopsychismus and Artificial Intelligence: Infopsychismus_Book/16_Infopsychismus_and_Artificial_Intelligence.md
      - Infopsychismus and the Limits of Computation and Simulation: Infopsychismus_Book/17_Infopsychismus_and_the_Limits_of_Computation_and_Simulation.md
      - Infopsychismus and Philosophy of Language: Infopsychismus_Book/18_Infopsychismus_and_Philosophy_of_Language.md
      - Extended Reflections on Meaning: Infopsychismus_Book/19_Extended_Reflections_on_Meaning.md
      - Glossary: Infopsychismus_Book/20_Glossary.md
      - Contributors: Infopsychismus_Book/21_Contributors.md
      - Change Log: Infopsychismus_Book/22_Change_Log.md
      - References and Sources: Infopsychismus_Book/23_References_and_Sources.md
  - Infopsychismus Origins: Infopsychismus.txt
  - Other Languages:
      - "العربية (كتاب)": languages/ar/Infopsychismus_Kitab_Takamuli_AR/00_الفهرس.md
      - "Deutsch (Buch)": languages/de/Infopsychismus_Ein_Integratives_Buch_DE/00_Inhaltsverzeichnis.md
      - "Español (Libro)": languages/es/Infopsiquismo_Un_Libro_Integrativo_ES/00_Tabla_de_contenidos.md
      - "Français (Livre)": languages/fr/Infopsychisme_Un_Livre_Intégratif_FR/00_Table_des_matières.md
      - "हिन्दी (पुस्तक)": languages/hi/Infopsychismus_Samagra_Pustak_HI/00_सामग्री_सूची.md
      - "Italiano (Libro)": languages/it/Infopsichismo_Un_Libro_Integrativo_IT/00_Indice.md
      - "日本語 (書籍)": languages/ja/Infopsychismus_Togo_Teki_Chosaku_JA/00_目次.md
      - "한국어 (책)": languages/ko/Infopsychismus_Tonghapjeok_Jeojak_KO/00_목차.md
      - "Português (Livro)": languages/pt/Infopsiquismo_Um_Livro_Integrativo_PT/00_Índice.md
      - "Русский (Книга)": languages/ru/Infopsikhizm_Integrativnaya_Kniga_RU/00_Оглавление.md
      - "Türkçe (Kitap)": languages/tr/Infopsisizm_Butunleyici_Kitap_TR/00_İçindekiler.md
      - "中文 (书籍)": languages/zh/Infopsychismus_Yi_Zhong_He_Xing_Zhu_Zuo_ZH/00_目录.md
