docs_dir: docs
site_dir: _site
site_name: Infopsychismus – An Integrative Book on Consciousness, Reality, and Meaning
nav:
  - Home: Infopsychismus.txt
  - Book:
      - Table of Contents: Infopsychismus_Book/00_Table_of_Contents.md
      - Introduction: Infopsychismus_Book/01_Introduction.md
      - 1. The Question of Existence: Infopsychismus_Book/02_The_Question_of_Existence.md
      - 2. The Structure of Reality: Infopsychismus_Book/03_The_Structure_of_Reality.md
      - 3. The Role of Consciousness: Infopsychismus_Book/04_The_Role_of_Consciousness.md
      - 4. Why Are We Conscious Beings Here?: Infopsychismus_Book/05_Why_Are_We_Conscious_Beings_Here.md
      - 5. Our Actual Task: Infopsychismus_Book/06_Our_Actual_Task.md
      - 6. Outlook and Ethical Implications: Infopsychismus_Book/07_Outlook_and_Ethical_Implications.md
      - 7. The Future of Consciousness: Infopsychismus_Book/08_The_Future_of_Consciousness.md
      - 8. Toward Planetary and Cosmic Consciousness: Infopsychismus_Book/09_Toward_Planetary_and_Cosmic_Consciousness.md
      - 9. The Practice of Infopsychismus: Infopsychismus_Book/10_Historical_Context_and_Intellectual_Lineage.md
      - 10. Infopsychismus and the Future of Meaning: Infopsychismus_Book/11_Case_Studies_and_Real-World_Applications.md
      - 11. Open Questions and Future Research Directions: Infopsychismus_Book/12_Criticisms_and_Counterarguments.md
      - 12. Historical Context and Intellectual Lineage: Infopsychismus_Book/13_Methodology_and_Epistemology.md
      - 13. Case Studies and Real-World Applications: Infopsychismus_Book/14_Deeper_Exploration_of_Ethics.md
      - 14. Criticisms and Counterarguments: Infopsychismus_Book/15_Annexes_and_Further_Reading.md
      - 15. Methodology and Epistemology: Infopsychismus_Book/16_Infopsychismus_and_Artificial_Intelligence.md
      - 16. Deeper Exploration of Ethics: Infopsychismus_Book/17_Infopsychismus_and_Computation.md
      - 17. Appendices and Further Reading: Infopsychismus_Book/18_Infopsychismus_and_Philosophy_of_Language.md
      - 18. Infopsychismus and Artificial Intelligence: Infopsychismus_Book/19_Extended_Reflections_on_Meaning.md
      - 19. Infopsychismus and the Limits of Computation and Simulation: Infopsychismus_Book/20_Glossary.md
      - 20. Infopsychismus and the Philosophy of Language: Infopsychismus_Book/22_Change_Log.md
      - 21. Expanded Reflections on Meaning: Infopsychismus_Book/23_References_and_Sources.md
  - Infopsychismus Origins: Infopsychismus.txt
  - Other Languages:
      - "Deutsch (Buch)": languages/de/Infopsychismus_Ein_Integratives_Buch_DE/00_Inhaltsverzeichnis.md
      - "Français (Livre)": languages/fr/Infopsychisme_Un_Livre_Intégratif_FR/00_Table_des_matières.md
      - "Español (Libro)": languages/es/Infopsiquismo_Un_Libro_Integrativo_ES/00_Tabla_de_contenidos.md
      - "中文 (书籍)": languages/zh/Infopsychismus_Yi_Zhong_He_Xing_Zhu_Zuo_ZH/00_目录.md
      - "Русский (Книга)": languages/ru/Infopsikhizm_Integrativnaya_Kniga_RU/00_Оглавление.md
      - "Português (Livro)": languages/pt/Infopsiquismo_Um_Livro_Integrativo_PT/00_Índice.md
      - "日本語 (書籍)": languages/ja/Infopsychismus_Togo_Teki_Chosaku_JA/00_目次.md
      - "한국어 (책)": languages/ko/Infopsychismus_Tonghapjeok_Jeojak_KO/00_목차.md
      - "Türkçe (Kitap)": languages/tr/Infopsisizm_Butunleyici_Kitap_TR/00_İçindekiler.md
