docs_dir: docs
site_name: Infopsychismus – An Integrative Book on Consciousness, Reality, and Meaning
nav:
  - Home: README.md
  - Book:
      - Foreword: Infopsychismus_Book.md
      - Table of Contents: Infopsychismus_Book.md
      - Introduction: Infopsychismus_Book.md
      - "1. The Question of Existence": Infopsychismus_Book.md
      - "2. The Structure of Reality": Infopsychismus_Book.md
      - "3. The Role of Consciousness": Infopsychismus_Book.md
      - "4. Why Are We Conscious Beings Here?": Infopsychismus_Book.md
      - "5. Our Actual Task": Infopsychismus_Book.md
      - "6. Outlook and Ethical Implications": Infopsychismus_Book.md
      - "7. The Future of Consciousness: Technology, Society, and Evolution": Infopsychismus_Book.md
      - "8. Toward Planetary and Cosmic Consciousness": Infopsychismus_Book.md
      - "9. The Practice of Infopsychismus: Living the Model": Infopsychismus_Book.md
      - "10. Infopsychismus and the Future of Meaning": Infopsychismus_Book.md
      - "11. Open Questions and Future Research Directions": Infopsychismus_Book.md
      - "12. Historical Context and Intellectual Lineage": Infopsychismus_Book.md
      - "13. Case Studies and Real-World Applications": Infopsychismus_Book.md
      - "14. Criticisms and Counterarguments": Infopsychismus_Book.md
      - "15. Methodology and Epistemology": Infopsychismus_Book.md
      - "16. Deeper Exploration of Ethics": Infopsychismus_Book.md
      - "17. Appendices and Further Reading": Infopsychismus_Book.md
      - "18. Infopsychismus and Artificial Intelligence: Challenges and Opportunities": Infopsychismus_Book.md
      - "19. Infopsychismus and the Limits of Computation and Simulation": Infopsychismus_Book.md
      - "20. Infopsychismus and the Philosophy of Language": Infopsychismus_Book.md
      - "21. Expanded Reflections on Meaning": Infopsychismus_Book.md
      - Glossary: Infopsychismus_Book.md
      - Contributors: Infopsychismus_Book.md
      - Change Log: Infopsychismus_Book.md
      - References and Sources: Infopsychismus_Book.md
  - Infopsychismus Origins: Infopsychismus.txt
  - Other Languages:
      - "Deutsch (Buch)": languages/de/Infopsychismus_Ein_Integratives_Buch_DE.md
      - "Deutsch (Projektinfo)": languages/de/README_DE.md
      - "Deutsch (Text)": languages/de/Infopsychismus_DE.txt
      - "Français (Livre)": languages/fr/Infopsychisme_Un_Livre_Intégratif_FR.md
      - "Français (Projet)": languages/fr/README_FR.md
      - "Español (Libro)": languages/es/Infopsiquismo_Un_Libro_Integrativo_ES.md
      - Español (Proyecto): languages/es/README_ES.md
      - "中文 (书籍)": languages/zh/Infopsychismus_Yi_Zhong_He_Xing_Zhu_Zuo_ZH.md
      - "中文 (项目信息)": languages/zh/README_ZH.md
      - "Русский (Книга)": languages/ru/Infopsikhizm_Integrativnaya_Kniga_RU.md
      - "Русский (Проект)": languages/ru/README_RU.md
